# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-18 17:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rainfall'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rainfall',
            name='date',
        ),
    ]
