# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-18 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_rainfall_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('rain_length', models.DecimalField(decimal_places=10, max_digits=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Rainfall',
        ),
    ]
