# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-29 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180318_2338'),
    ]

    operations = [
        migrations.CreateModel(
            name='DamWaterYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('mean_discharge', models.DecimalField(decimal_places=10, max_digits=20)),
            ],
        ),
    ]
