# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-29 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_damwateryear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='damwateryear',
            name='month',
            field=models.CharField(max_length=10),
        ),
    ]
