# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-29 07:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_damwaterday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='damwaterday',
            old_name='date',
            new_name='Date',
        ),
        migrations.RenameField(
            model_name='damwaterday',
            old_name='discharge',
            new_name='Discharge',
        ),
    ]
