# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-29 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_roadsubmergenceday'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoadSubmergenceYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=10)),
                ('monthly_discharge', models.DecimalField(decimal_places=10, max_digits=20)),
                ('rain_safe', models.CharField(max_length=10)),
            ],
        ),
    ]
